none

diff --git a/scripts/run_episode b/scripts/run_episode
--- a/scripts/run_episode
+++ b/scripts/run_episode
@@ -1,18 +1,28 @@
 #!/bin/bash
 if (($# < 7)); then
   echo "usage:"
-  echo "   run_episode [repetitions] [world_name] [log_file] [planning_iteration] [k] [pred_starting_pos_x] [pred_starting_pos_y] [randomness] [path_type]"
+  echo "   run_episode [repetitions] [world_name] [planning_iteration] [particles] [pred_starting_pos_x] [pred_starting_pos_y] [randomness] [path_type]"
 else
-  R=$1
-  nx=$(($6 - 7))
-  ny=$((-($7 - 7)))
-  for ((I = 1; I <= $R; I++)); do
-    echo "./habit $2 -seed $I -pi $4 -k $5 -slx $nx -sly $ny -pr $8 -path $9"
-    HABIT=$(./habit $2 -seed $I -pi $4 -k $5 -slx $nx -sly $ny -pr $8 -path $9)
+  world=$2
+  planning_iterations=$3
+  particles=$4
+  x=$5
+  y=$6
+  randomness=$7
+  path_type=$8
+  repetitions=$1
+  nx=$(($x - 7))
+  ny=$((-($y - 7)))
+  for ((seed = 1; seed <= $repetitions; seed++)); do
+    episode="./habit $world -seed $seed -pi $planning_iterations -k $particles -slx $nx -sly $ny -pr $randomness -path $path_type"
+    result=$($episode)
     if [ $? -ne 0 ]; then
-      echo "FAILED: ./habit $2 -seed $I -pi $4 -k $5 -slx $nx -sly $ny -pr $8 -path $9 ($6;$7)" >&2
+      echo "FAILED: $episode ($x;$y)" >&2
     else
-      echo "{ 'seed': $I, 'predator_start_location': {'x': $6,'y': $7},'result': $HABIT }," >>${3}
+      echo "{ \"seed\": $seed, \"predator_start_location\": [$x,$y],\"result\": $result }"
+      if (( seed < repetitions )); then
+        printf ","
+      fi
     fi
   done
 fi
